sudo: false
language: php
dist: trusty

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

services:
    - mysql
    - postgresql

matrix:
    fast_finish: true

before_script:
    - touch ./tests/php.ini
    - cp ./tests/drivers.sample.ini ./tests/drivers.ini

    - psql -c 'CREATE DATABASE nextras_migrations_test' -U postgres
    - mysql -e 'CREATE DATABASE nextras_migrations_test;'
    - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

    - composer self-update
    - composer install --no-interaction --no-progress

script:
    - ./tests/run-unit.sh
    - ./tests/run-integration.sh
